### ISSUE TITLE
Cannot create workspace

### ISSUE THREAD

**Issue by tehlowkeywiz** [telefuel/telefuel-roadmap#27]
When clicking the "New Workspace" button or doing the keyboard shortcut, nothing happens and I cannot create a new workspace. Also, right-clicking on a channel and selecting copy to workspace opens a modal, in which there is a "NEW WORKSPACE" button. That button also doesn't do anything.

I'm using Telefuel v.0.2.4
macOS Catalina 10.15.2 (19C57)

**Comment by ladygin-me** [comment]
The same problem

**Comment by MattNguyen** [comment]
@saneklad @phila82r can you all try clearing data from the menu and signing back in?

**Comment by ladygin-me** [comment]
@MattNguyen no, it did not help. Web, Windows app - the same situation. I have PRO after referring a friend.

**Comment by tehlowkeywiz** [comment]
Same, didn't change anything.

**Comment by MattNguyen** [comment]
Are these fairly new accounts? Did you use the multi-account feature? 

Apologies for the questions, but I'm trying to replicate.

**Comment by tehlowkeywiz** [comment]
On my side, I opened my account yesterday - so brand new.

**Comment by ladygin-me** [comment]
@MattNguyen I opened account yesterday too (have 2FA), didn't use multi-acc. 
I added second one for test today only, but situation is the same.

**Comment by MattNguyen** [comment]
@saneklad @phila82r this is fixed. Please reload the app to get the latest changes.
